### ISSUE TITLE
Handle `CLEARMSG` messages while converting to `NOTICE`

### ISSUE THREAD

**Issue by zneix** [robotty/recent-messages2#251]
Upon deleting a single message from a user (instead of timing them out, banning or clearing chat) Twitch returns `target-msg-id` tag containing ID of the single message that has been deleted in `CLEARMSG` message.

Example (I deleted my message in my own chat):
`@login=zneix;room-id=;target-msg-id=91061af6-fad1-49a1-8b33-0c131cc297b6;tmi-sent-ts=1626452108291 :tmi.twitch.tv CLEARMSG #zneix :-tags`

As spotted on https://recent-messages.robotty.de/api I see that `?clearchat_to_notice=true` covers three `msg-id`s for different kinds of `CLEARCHAT` messages (`rm-clearchat` `rm-timeout` `rm-permaban`), but `CLEARMSG` isn't taken into account at all.
While I realize it is another message, other than `CLEARCHAT`, I think it's worth taking `CLEARMSG` messages into account while using `?clearchat_to_notice=true` param or introducing something like `?clearmsg_to_notice=true`.

I'd suggest adding handling for those kinds of messages and introducing of a new `msg-id`, e.g.: `rm-msg` or `rm-msg-deleted`.

**Comment by RAnders00** [comment]
What do you imagine those NOTICE messages should look like (what text should they have)?

When I made `clearchat_to_notice`, I made it as a temporary workaround for Chatterino that didn‘t show CLEARCHAT messages in the message history if I just returned them from my API as CLEARCHAT.

I also documented this on the website a while ago:

![2AE93A5F-1CEB-4FA4-835F-610A2E724EAD](https://user-images.githubusercontent.com/1629196/126385530-238f30eb-23b2-4d61-b6a3-3f938e571725.jpeg)

With this in mind, what‘s the use case for the new option/expanding the existing one?
