### ISSUE TITLE
Is there any chrome extension that utilises this repo?

### ISSUE THREAD

**Issue by Nerxxy** [robotty/recent-messages2#283]
title.

**Comment by RAnders00** [comment]
Not that I‘m aware of, and I didn‘t even consider it necessary since Twitch provides this service first-party. I‘m curious why you‘re asking though!

**Comment by Nerxxy** [comment]
to be honest its not actually necessary, i personally use 7tv as well as ffz extensions and theres a compatibility issue where the recent messages dont show in a channel thats been opened into a new tab, so i was just wondering if there was an extension to essentially force the recent messages to appear.
