### ISSUE TITLE
Giving broadcasters control; concurrent join limits for IRC and EventSub

### ISSUE THREAD

**Issue by i3eta22** [robotty/recent-messages2#291]
https://discuss.dev.twitch.com/t/giving-broadcasters-control-concurrent-join-limits-for-irc-and-eventsub/54997

Will this change negatively impact the service provided by the API?

**Comment by RAnders00** [comment]
This service won‘t be affected, since it uses anonymous IRC connections, and makes multiple connections, each one connecting to <100 by default (https://docs.rs/twitch-irc/latest/src/twitch_irc/config.rs.html#166). Thank you for bringing that blog post to my attention though!
